### ISSUE TITLE
cannot process file

### ISSUE THREAD

**Issue by anne1994** [lixiangchun/mynotebook#1]
@lixiangchun i was trying to do the same way as you did. But though i pass a jpeg image the code says image cannot process.

**Comment by lixiangchun** [comment]
Could you share your jpeg image with me? I can try it on my computer to see what will happen and get you my feedback.

**Comment by anne1994** [comment]
can i email you? @lixiangchun

**Comment by anne1994** [comment]
@lixiangchun  also my infile has a path to a jpg.  
Example: "**c:/users/....images/example.jpg** " 

If i have multiple images, should it be only the directory where i have multiple jpg images? 
example: **c:/users/../images/** 

could you tell me the right format, as i am confused regarding the infile?

**Comment by anne1994** [comment]
Hi @lixiangchun I am able to process the image, show the probabilities :) . 
But i get this wierd looking display as well. is it ok ?
![screenshot 25](https://user-images.githubusercontent.com/26388650/28281402-cd083c32-6adb-11e7-8363-4f5017985759.png)

**Comment by lixiangchun** [comment]
1. The `infile` option refers to a text file with path to images being classified. E.g. if you have multiple files i.e. x1.jpg, x2.jpg and x3.jpg, the `infile` refers to a text file looks like:
```
x1.jpg
x2.jpg
x3.jpg
```
2. I haven't encounter the weird looking display. I only tested `classify_image.py` on Linux platform.

You can upload your image to google drive and share it with me.

**Comment by anne1994** [comment]
ok. Can i get your email id? 

I am connected as a remote host through putty. That maybe the reason for "putty"displaying. Dont know why. 

Also is there anyway to display the labels instead of displaying classes0,class1 , ... 
can we map them? 

I have seen this https://github.com/petewarden/tensorflow_makefile/blob/master/tensorflow/models/image/imagenet/classify_image.py which converts the nodeid to human_readable_strings. But not sure on how to tweak it in a way suitable for eval_image_classifier code.

**Comment by anne1994** [comment]
Hi, Yes i could print the labels now after changing some code from classify_image.

 Can you check my image on your system and see if you get the weird display?

**Comment by anne1994** [comment]
everything is fine now. no weird display. I was printing image read by mistake and hence the display.
